name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean up CI
        run: |
          df -h
          curl -s https://github.com/apache/flink/raw/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh | bash
          df -h

      - name: Set up QEMU
        if: ${{ !contains(github.event.commits[0].message, '[test]') }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/nng4
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build Multi-platform image
        uses: docker/build-push-action@v5
        if: ${{ !contains(github.event.commits[0].message, '[test]') }}
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nng4:latest
          cache-to: type=inline
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/loong64,linux/arm/v7,linux/arm/v6

      - name: Build test image
        uses: docker/build-push-action@v5
        if: ${{ contains(github.event.commits[0].message, '[test]') }}
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nng4:latest
          cache-to: type=inline
          load: true

      - name: Save Docker image as tar file
        if: ${{ contains(github.event.commits[0].message, '[test]') }}
        run: |
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/nng4 -o nng4-images.tar

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        if: ${{ contains(github.event.commits[0].message, '[test]') }}
        with:
          name: docker-image-tar
          path: nng4-images.tar

      - name: Test Docker container and output logs
        if: ${{ contains(github.event.commits[0].message, '[test]') }}
        run: |
          docker images
          docker run -d -p 3000:3000 --name test-container ${{ secrets.DOCKERHUB_USERNAME }}/nng4
          sleep 20
          docker logs test-container
          response=$(curl -s http://127.0.0.1:3000/data/g/local/nng4/game.json)
          if [ -z "$response" ]; then
              echo "Error: curl returned empty response" >&2
              docker logs test-container
              exit 1
          else
              echo "Response received: $response"
          fi
          sleep 5
          docker logs test-container
          docker stop test-container
          docker rm test-container

      - name: Push Docker image
        if: ${{ !contains(github.event.commits[0].message, '[test]') }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nng4:latest
          cache-to: type=inline
          push: true