name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SKIP_PUSH: ${{ contains(github.event.commits[0].message, '[skip-push]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/nng4
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ !env.SKIP_PUSH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nng4:latest
          cache-to: type=inline
          outputs: type=docker,dest=/tmp/nng4.tar

      - name: Test Docker container and output logs
        run: |
          echo "Push ${{ !env.SKIP_PUSH }}"
          docker load -i /tmp/nng4.tar
          docker images
          docker run -d --port 3000:3000 --name test-container ${{ secrets.DOCKERHUB_USERNAME }}/nng4
          sleep 20
          docker logs test-container
          curl http://127.0.0.1:3000/
          sleep 5
          docker logs test-container
          docker stop test-container
          docker rm test-container
